name: Build and Deploy React to Rocky Linux

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      # Force legacy peer deps to allow npm install to work with mismatched dependencies
      NPM_CONFIG_LEGACY_PEER_DEPS: true
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # Use Node.js 14 which doesn't require the OpenSSL legacy provider flag
          node-version: '14'
      
      - name: Delete package-lock.json and node_modules
        run: |
          rm -f package-lock.json
          rm -rf node_modules
      
      - name: Install jq utility
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Update package.json Babel dependencies
        run: |
          # Use jq to update Babel dependencies
          jq '.dependencies["@babel/core"] = "^7.16.0"' package.json > package.json.tmp && mv package.json.tmp package.json
          jq '.dependencies["babel-preset-react-app"] = "^10.0.0"' package.json > package.json.tmp && mv package.json.tmp package.json
      
      - name: Install dependencies
        run: |
          npm install --no-package-lock
          # Explicitly install correct Babel version
          npm install --no-package-lock @babel/core@^7.16.0 babel-preset-react-app@^10.0.0
      
      - name: Build React app
        run: npm run build
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      
      - name: Deploy with rsync
        run: |
          rsync -avz -e "ssh -p ${{ secrets.SSH_PORT || '22' }}" --delete ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/share/nginx/react
      
      - name: Verify deployment and set permissions
        run: |
          ssh -p ${{ secrets.SSH_PORT || '22' }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            sudo chown -R nginx:nginx /usr/share/nginx/react &&
            sudo chmod -R 755 /usr/share/nginx/react &&
            ls -la /usr/share/nginx/react
          "