name: Build and Deploy React to Rocky Linux

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      # Fix Node.js OpenSSL issues with older React scripts
      NODE_OPTIONS: --openssl-legacy-provider
      # Force legacy peer deps to allow npm install to work with mismatched dependencies
      NPM_CONFIG_LEGACY_PEER_DEPS: true
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Delete package-lock.json
        run: rm -f package-lock.json
      
      - name: Install dependencies
        run: npm install --no-package-lock
      
      - name: Build React app
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: build/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-files
          path: build
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      
      - name: Deploy with rsync
        run: |
          rsync -avz -e "ssh -p ${{ secrets.SSH_PORT || '22' }}" --delete ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/usr/share/nginx/react
      
      - name: Verify deployment and set permissions
        run: |
          ssh -p ${{ secrets.SSH_PORT || '22' }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            sudo chown -R nginx:nginx /usr/share/nginx/react &&
            sudo chmod -R 755 /usr/share/nginx/react &&
            ls -la /usr/share/nginx/react
          "