name: Build and Deploy React to Rocky Linux

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    env:
      # Force legacy peer deps to allow npm install to work with mismatched dependencies
      NPM_CONFIG_LEGACY_PEER_DEPS: true
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check Node.js version
        run: node --version
      
      - name: Delete package-lock.json and node_modules
        run: |
          rm -f package-lock.json
          rm -rf node_modules
      
      - name: Install dependencies
        run: |
          npm install --no-package-lock
      
      - name: Update Babel dependencies
        run: |
          npm install --no-package-lock @babel/core@^7.16.0 babel-preset-react-app@^10.0.0
      
      - name: Build React app with legacy OpenSSL
        run: |
          # Use the OpenSSL legacy provider flag to fix Node.js crypto issues
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
      
      - name: Deploy to Nginx directory
        run: |
          # Create the directory if it doesn't exist
          sudo mkdir -p /usr/share/nginx/react

          # Copy build files directly to Nginx directory
          sudo cp -r ./build/* /usr/share/nginx/react/
          
          # Set proper permissions
          sudo chown -R nginx:nginx /usr/share/nginx/react
          sudo chmod -R 755 /usr/share/nginx/react
      
      - name: Verify deployment
        run: ls -la /usr/share/nginx/react